on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - run: |
          mvn --update-snapshots --batch-mode install
        env:
          GITHUB_TOKEN: ${{secrets.MAVEN}}
      - run: |
          mvn --batch-mode exec:java -Dexec.mainClass="world.Hello"

